package com.GuidePro.nlp;


import java.util.*;

public class IntentClassifier {

    private Map<String, List<String>> intentMap;

    public IntentClassifier() {
        intentMap = new HashMap<>();
        initializeIntents();
    }

    private void initializeIntents() {
        // Example intents with sample utterances
    	intentMap.put("GetDestinationInfo", Arrays.asList(
    		    "tell me about", 
    		    "famous for", 
    		    "information on", 
    		    "describe", 
    		    "overview of", 
    		    "details about", 
    		    "what is", 
    		    "what's", 
    		    "known for", 
    		    "history of", 
    		    "background of", 
    		    "where is", 
    		    "location of", 
    		    "what can you tell me about", 
    		    "give me info on", 
    		    "explain about", 
    		    "what is special about", 
    		    "features of",
    		    "interesting facts about", 
    		    "insights on", 
    		    "summary of", 
    		    "key points about", 
    		    "give an account of", 
    		    "reputation of", 
    		    "importance of", 
    		    "why is it famous", 
    		    "why visit", 
    		    "main attractions in", 
    		    "brief on", 
    		    "unique about", 
    		    "noteworthy aspects of", 
    		    "what makes it unique", 
    		    "highlight of", 
    		    "tell me something about", 
    		    "main features of", 
    		    "what should I know about", 
    		    "popular for", 
    		    "identity of", 
    		    "significance of", 
    		    "tell me the story of", 
    		    "cultural aspects of", 
    		    "main landmarks in", 
    		    "symbol of", 
    		    "iconic aspects of",
    		    "what to know about", 
    		    "landmarks in", 
    		    "describe the", 
    		    "can you tell me about", 
    		    "what's there to see in", 
    		    "characteristics of", 
    		    "what's it like", 
    		    "what is it like", 
    		    "best things about", 
    		    "what makes it special", 
    		    "what's interesting about", 
    		    "tell me more about", 
    		    "factors that define", 
    		    "what's the significance of", 
    		    "what's important about", 
    		    "background story of", 
    		    "historical significance of", 
    		    "importance in history of", 
    		    "legacy of", 
    		    "why is it a must-visit", 
    		    "describe its", 
    		    "what is unique about", 
    		    "defining characteristics of", 
    		    "distinct features of", 
    		    "what should I see in", 
    		    "essence of", 
    		    "what embodies", 
    		    "notable features of", 
    		    "defining features of", 
    		    "fascinating facts about", 
    		    "why is it noteworthy", 
    		    "what's so special about", 
    		    "highlight its", 
    		    "prominent features of", 
    		    "key characteristics of", 
    		    "what stands out about", 
    		    "what's the vibe of", 
    		    "the spirit of", 
    		    "the soul of", 
    		    "the atmosphere in", 
    		    "what defines", 
    		    "why people visit", 
    		    "major highlights of", 
    		    "notable landmarks in", 
    		    "must-see aspects of"
    		));
    	intentMap.put("GetTopAttractions", Arrays.asList(
    		    "must-see places", 
    		    "top attractions", 
    		    "things to do", 
    		    "sights", 
    		    "places to visit", 
    		    "points of interest", 
    		    "tourist spots", 
    		    "famous landmarks", 
    		    "what to see", 
    		    "what to do", 
    		    "best places to visit", 
    		    "notable sites", 
    		    "must-visit places", 
    		    "popular spots", 
    		    "tourist destinations", 
    		    "highlights", 
    		    "key attractions", 
    		    "iconic places", 
    		    "places of interest", 
    		    "main attractions", 
    		    "must-experience", 
    		    "places worth visiting", 
    		    "what to explore", 
    		    "must-see sights", 
    		    "unmissable places", 
    		    "what not to miss", 
    		    "essential places to see", 
    		    "recommended places", 
    		    "what to check out", 
    		    "sightseeing spots", 
    		    "tourist attractions", 
    		    "best things to see",
    		    "major attractions", 
    		    "where to go", 
    		    "what's popular", 
    		    "where to visit", 
    		    "top things to see", 
    		    "where should I go", 
    		    "must-visit spots", 
    		    "famous sites", 
    		    "don't miss", 
    		    "what to experience", 
    		    "highlight spots", 
    		    "important sites", 
    		    "landmarks to visit", 
    		    "key places", 
    		    "most popular places", 
    		    "essential sights", 
    		    "iconic attractions", 
    		    "can't-miss spots", 
    		    "significant attractions", 
    		    "top-rated places", 
    		    "main tourist spots", 
    		    "tourism highlights", 
    		    "top sites", 
    		    "where to go first", 
    		    "best experiences", 
    		    "most visited places", 
    		    "what to see first", 
    		    "top things to do",
    		    "where to sightsee", 
    		    "must-see destinations", 
    		    "best sightseeing", 
    		    "places to explore", 
    		    "key tourist spots", 
    		    "iconic sights", 
    		    "where to start", 
    		    "first-time visit", 
    		    "best tourist spots", 
    		    "essential visits", 
    		    "top locations", 
    		    "where to find", 
    		    "must-visit destinations", 
    		    "where to explore", 
    		    "must-see attractions", 
    		    "prime locations", 
    		    "tourism spots", 
    		    "key destinations", 
    		    "not-to-miss", 
    		    "best places for sightseeing", 
    		    "where to go for", 
    		    "important landmarks", 
    		    "top experiences", 
    		    "iconic landmarks", 
    		    "recommended sights", 
    		    "what to see around", 
    		    "best places around", 
    		    "sightseeing musts", 
    		    "main sights", 
    		    "what's worth seeing", 
    		    "best spots to visit", 
    		    "popular tourist attractions", 
    		    "unmissable attractions", 
    		    "must-see landmarks", 
    		    "tourist musts", 
    		    "highlights of", 
    		    "where to wander", 
    		    "prime sightseeing spots"
    		));
    	intentMap.put("GetBestTimeToVisit", Arrays.asList(
    		    "best time to visit", 
    		    "weather in", 
    		    "climate in", 
    		    "when to visit", 
    		    "ideal time to visit", 
    		    "season to visit", 
    		    "when is the best time", 
    		    "best season to visit", 
    		    "recommended time to visit", 
    		    "weather conditions in", 
    		    "what's the weather like in", 
    		    "when should I visit", 
    		    "when's the best time to go", 
    		    "perfect time to visit", 
    		    "optimal time to visit", 
    		    "best months to visit", 
    		    "what's the climate like", 
    		    "what time of year to visit", 
    		    "best period to visit", 
    		    "when is peak season", 
    		    "when is off-season", 
    		    "most popular time to visit", 
    		    "best weather for visit", 
    		    "when is the high season", 
    		    "best time of year to visit", 
    		    "when does the weather get good", 
    		    "when is it less crowded", 
    		    "ideal months to visit", 
    		    "best time for good weather", 
    		    "when is the weather favorable", 
    		    "when's the weather best", 
    		    "suitable time to visit", 
    		    "what's the best climate", 
    		    "what's the weather like", 
    		    "which season is best", 
    		    "weather patterns in", 
    		    "best time to explore", 
    		    "best conditions for visiting", 
    		    "when is the temperature best", 
    		    "when is it sunny", 
    		    "when is it dry", 
    		    "best time to enjoy the weather", 
    		    "which months are best", 
    		    "best travel season", 
    		    "what's the best time of year", 
    		    "weather forecast for", 
    		    "best time for outdoor activities", 
    		    "when is the monsoon season", 
    		    "when does it rain", 
    		    "when is the rainy season", 
    		    "when is it hot", 
    		    "when is it cold", 
    		    "when are the festivals", 
    		    "when is it warm", 
    		    "when is the snow season", 
    		    "best season for sightseeing", 
    		    "when to avoid crowds", 
    		    "when is the beach season", 
    		    "when to avoid", 
    		    "peak tourist season", 
    		    "off-peak season", 
    		    "weather advice for", 
    		    "when is it busiest", 
    		    "quiet season to visit", 
    		    "when is hurricane season", 
    		    "when is the best weather", 
    		    "ideal weather for visit", 
    		    "when is the coolest weather", 
    		    "most comfortable time to visit", 
    		    "when is the driest weather", 
    		    "best time for hiking", 
    		    "best time for beach", 
    		    "when is the sunniest", 
    		    "when is it foggy", 
    		    "when does it snow", 
    		    "best months for travel", 
    		    "when is the peak weather", 
    		    "when is it stormy", 
    		    "best time for festivals", 
    		    "when is it mild", 
    		    "when is the tourist season", 
    		    "best months for sightseeing", 
    		    "when is the low season", 
    		    "best time for a visit",
    		    "when is the weather perfect", 
    		    "when is it best to travel", 
    		    "when should I avoid", 
    		    "when is the least rain", 
    		    "when is the least snow", 
    		    "what's the best time for a tour", 
    		    "best time for adventure", 
    		    "when is it the least crowded", 
    		    "when's the weather ideal", 
    		    "when does it get too hot", 
    		    "when is it coolest", 
    		    "when is the tourist rush", 
    		    "when does it get windy", 
    		    "when is it calm", 
    		    "when is the low tourist season", 
    		    "when are there fewer tourists", 
    		    "what's the off-season", 
    		    "what's the low season", 
    		    "what's the high season", 
    		    "when is it least busy", 
    		    "what time of year is best", 
    		    "when is the sunniest season", 
    		    "what's the least crowded time", 
    		    "best time to avoid bad weather", 
    		    "when is it clearest", 
    		    "what's the warmest season", 
    		    "when is the least humid", 
    		    "when does the rain stop", 
    		    "when is the coldest", 
    		    "when is the driest", 
    		    "when does it start raining", 
    		    "when does the rain begin", 
    		    "when does the snow begin", 
    		    "when does it start snowing", 
    		    "when does it start getting hot", 
    		    "when does it start getting cold", 
    		    "when does the humidity drop", 
    		    "when is the wet season", 
    		    "when is the dry season", 
    		    "when is the hottest month", 
    		    "when is the coldest month", 
    		    "when are the warmest days", 
    		    "when are the coolest days", 
    		    "when is the hottest day", 
    		    "when is the coldest day", 
    		    "when is it least likely to rain", 
    		    "when is it most likely to rain", 
    		    "when is the rainiest season", 
    		    "when does it stop snowing", 
    		    "when does the snow melt", 
    		    "when is it greenest", 
    		    "when does the foliage peak", 
    		    "when are the longest days", 
    		    "when are the shortest days", 
    		    "when is the sunset latest", 
    		    "when is the sunrise earliest", 
    		    "when is the daylight longest", 
    		    "when is the daylight shortest", 
    		    "when are the clearest skies", 
    		    "when is it most overcast", 
    		    "when is it least overcast", 
    		    "when is it brightest", 
    		    "when is the night longest", 
    		    "when is the night shortest", 
    		    "when are the nights longest", 
    		    "when are the nights shortest"
    		));
    	intentMap.put("GetLocalTransportation", Arrays.asList(
    		    "get around", 
    		    "public transportation", 
    		    "transport options", 
    		    "commute", 
    		    "how to travel locally", 
    		    "local transport", 
    		    "local transit", 
    		    "moving around", 
    		    "how to get around", 
    		    "best way to travel", 
    		    "getting around the city", 
    		    "local buses", 
    		    "local trains", 
    		    "metro system", 
    		    "subway routes", 
    		    "taxi services", 
    		    "ride-sharing", 
    		    "local taxis", 
    		    "car rentals", 
    		    "bike rentals", 
    		    "scooter rentals", 
    		    "walking routes", 
    		    "best ways to move around", 
    		    "how to commute", 
    		    "local transport facilities", 
    		    "public transit options", 
    		    "getting from place to place", 
    		    "transport choices", 
    		    "transportation in", 
    		    "local commuting options", 
    		    "local bus routes", 
    		    "best transport mode", 
    		    "how to reach destinations", 
    		    "city transport", 
    		    "local transportation guide", 
    		    "how to navigate the city", 
    		    "best way to get to", 
    		    "how to access", 
    		    "public transport availability", 
    		    "getting around town", 
    		    "city transit system", 
    		    "transportation networks", 
    		    "commuting in", 
    		    "local travel tips", 
    		    "how to move around", 
    		    "local ferry services", 
    		    "transportation options available", 
    		    "transit choices", 
    		    "local mobility", 
    		    "how to get from point A to B", 
    		    "how to go to", 
    		    "local roadways", 
    		    "public bus service", 
    		    "train schedules", 
    		    "subway options", 
    		    "city bus system", 
    		    "local shuttle services", 
    		    "how to reach by public transport", 
    		    "transit availability", 
    		    "traveling within the city", 
    		    "city transport details", 
    		    "how to get to places", 
    		    "public transit guide", 
    		    "local transport information", 
    		    "how to access transport", 
    		    "public transit tips", 
    		    "how to use public transportation", 
    		    "bus schedules", 
    		    "train routes", 
    		    "transportation services in", 
    		    "how to get around easily", 
    		    "local commute options", 
    		    "transport links", 
    		    "how to reach by train", 
    		    "local travel advice", 
    		    "local transport system", 
    		    "city transportation options", 
    		    "local transit advice", 
    		    "how to get there by bus", 
    		    "how to get there by train", 
    		    "public transportation options", 
    		    "what are the transit options", 
    		    "how to get from one place to another", 
    		    "how to use local transport", 
    		    "best way to get around town", 
    		    "how to find public transport", 
    		    "what are the local transit options", 
    		    "how to use city transport", 
    		    "best way to navigate the city", 
    		    "local transport routes", 
    		    "how to travel around the city", 
    		    "what's the best way to get around", 
    		    "how to access local transit", 
    		    "how to use public buses", 
    		    "what's the best public transport", 
    		    "what are the best ways to travel locally", 
    		    "local transport services", 
    		    "how to travel within the city", 
    		    "how to get around by train", 
    		    "how to get around by bus", 
    		    "what's the best transportation option", 
    		    "how to get from point A to B by public transport", 
    		    "how to use local shuttle services", 
    		    "how to use local taxis", 
    		    "best options for getting around", 
    		    "how to find the best transport options", 
    		    "what's the best transport mode for the city", 
    		    "how to get around without a car", 
    		    "how to get around during peak hours", 
    		    "how to get around on weekends", 
    		    "what are the options for getting around"
    		));
    	intentMap.put("GetAccommodationDining", Arrays.asList(
    		    "hotels in", 
    		    "restaurants in", 
    		    "where to stay", 
    		    "where to eat", 
    		    "best hotels in", 
    		    "top hotels in", 
    		    "places to stay", 
    		    "best restaurants in", 
    		    "top restaurants in", 
    		    "dining options in", 
    		    "where can I find hotels", 
    		    "where can I find restaurants", 
    		    "hotel recommendations", 
    		    "restaurant recommendations", 
    		    "accommodation options", 
    		    "dining places", 
    		    "where to find good hotels", 
    		    "where to find good restaurants", 
    		    "best places to stay", 
    		    "best places to eat", 
    		    "top dining spots", 
    		    "popular hotels in", 
    		    "popular restaurants in", 
    		    "best rated hotels", 
    		    "best rated restaurants", 
    		    "hotel reviews", 
    		    "restaurant reviews", 
    		    "where to have a meal", 
    		    "where to stay overnight", 
    		    "places for accommodation", 
    		    "places for dining", 
    		    "recommend hotels", 
    		    "recommend restaurants", 
    		    "where can I stay", 
    		    "where can I eat", 
    		    "good places to stay", 
    		    "good places to eat", 
    		    "hotel options", 
    		    "dining options", 
    		    "where to get lodging", 
    		    "where to get meals", 
    		    "recommended hotels", 
    		    "recommended restaurants", 
    		    "where to find lodging", 
    		    "where to find meals", 
    		    "hotels and dining", 
    		    "accommodation and dining options", 
    		    "hotel and restaurant suggestions", 
    		    "lodging options", 
    		    "meal options", 
    		    "best eateries in", 
    		    "best hotels near", 
    		    "where to dine out", 
    		    "places to eat out", 
    		    "local dining spots", 
    		    "local hotels", 
    		    "local eateries", 
    		    "where to stay in", 
    		    "where to eat in", 
    		    "top lodging options", 
    		    "top dining options", 
    		    "hotel deals", 
    		    "restaurant deals", 
    		    "luxury hotels in", 
    		    "budget hotels in", 
    		    "fine dining in", 
    		    "casual dining in", 
    		    "hotel and restaurant reviews", 
    		    "where to find good lodging", 
    		    "where to find good dining", 
    		    "accommodation near", 
    		    "restaurants near", 
    		    "hotels around", 
    		    "dining spots around", 
    		    "where to stay close to", 
    		    "where to eat close to", 
    		    "nearby hotels", 
    		    "nearby restaurants", 
    		    "best local hotels", 
    		    "best local restaurants", 
    		    "top local eateries", 
    		    "recommended dining places", 
    		    "recommended accommodation", 
    		    "where to stay on a budget", 
    		    "where to eat on a budget", 
    		    "best luxury dining", 
    		    "best affordable hotels", 
    		    "where to stay for families", 
    		    "where to eat with kids", 
    		    "pet-friendly hotels", 
    		    "vegetarian restaurants", 
    		    "vegan dining options", 
    		    "romantic restaurants", 
    		    "business hotels", 
    		    "family-friendly restaurants", 
    		    "high-end hotels", 
    		    "cheap eats", 
    		    "best brunch spots", 
    		    "best dinner spots", 
    		    "local food recommendations", 
    		    "best places for breakfast", 
    		    "best places for lunch", 
    		    "hotel amenities", 
    		    "restaurant amenities", 
    		    "what to look for in a hotel", 
    		    "what to look for in a restaurant", 
    		    "hotel price ranges", 
    		    "restaurant price ranges", 
    		    "hotels with breakfast", 
    		    "restaurants with outdoor seating", 
    		    "hotels with a view", 
    		    "restaurants with a view", 
    		    "places to stay with pool", 
    		    "places to eat with live music", 
    		    "best hotels for couples", 
    		    "best places for a romantic dinner", 
    		    "hotels with free Wi-Fi", 
    		    "restaurants with delivery options", 
    		    "hotels near attractions", 
    		    "restaurants near attractions", 
    		    "best places to stay for sightseeing", 
    		    "best places to eat near tourist spots"
    		));
    	intentMap.put("PlanItinerary", Arrays.asList(
    		    "itinerary for", 
    		    "plan trip to", 
    		    "days in", 
    		    "schedule for", 
    		    "what to do in", 
    		    "itinerary suggestion for", 
    		    "trip plan for", 
    		    "what to see in", 
    		    "how to spend days in", 
    		    "daily itinerary for", 
    		    "trip schedule for", 
    		    "travel plan for", 
    		    "suggestions for days in", 
    		    "activities for", 
    		    "best itinerary for", 
    		    "itinerary ideas for", 
    		    "how many days to spend in", 
    		    "day-by-day plan for", 
    		    "day-by-day itinerary for", 
    		    "things to do in", 
    		    "schedule of activities in", 
    		    "plan for visiting", 
    		    "recommended itinerary for", 
    		    "what to do each day in", 
    		    "how to plan a trip to", 
    		    "plan your visit to", 
    		    "best schedule for", 
    		    "plan for exploring", 
    		    "trip itinerary ideas", 
    		    "how to organize a trip to", 
    		    "activities schedule for", 
    		    "daily activities in", 
    		    "what to do every day in", 
    		    "trip itinerary suggestions", 
    		    "best days to spend in", 
    		    "itinerary recommendations", 
    		    "suggested travel plan for", 
    		    "suggested itinerary for", 
    		    "schedule of things to do in", 
    		    "plan your itinerary for", 
    		    "activities to include in", 
    		    "itinerary planning for", 
    		    "best way to spend days in", 
    		    "how to arrange your trip to", 
    		    "where to go each day in", 
    		    "ideal itinerary for", 
    		    "complete itinerary for", 
    		    "day planner for", 
    		    "suggested schedule for", 
    		    "trip activities planner", 
    		    "plan your daily schedule for", 
    		    "travel itinerary planner", 
    		    "how to structure your trip to", 
    		    "organize your trip to", 
    		    "how to allocate time in", 
    		    "plan day trips from", 
    		    "suggested activities for each day", 
    		    "how to map out your trip", 
    		    "what to prioritize in", 
    		    "best daily plan for", 
    		    "travel schedule suggestions", 
    		    "best daily itinerary", 
    		    "day-by-day schedule", 
    		    "custom itinerary for", 
    		    "personalized trip plan for", 
    		    "plan activities for", 
    		    "suggested schedule for visiting", 
    		    "itinerary breakdown for", 
    		    "daily itinerary planning for", 
    		    "activities and sightseeing in", 
    		    "how to schedule your trip to", 
    		    "ideal daily itinerary for", 
    		    "how to manage your time in", 
    		    "trip organization tips for", 
    		    "how to plan your days in", 
    		    "recommended schedule of activities", 
    		    "top activities to do each day", 
    		    "complete daily plan for", 
    		    "optimized itinerary for", 
    		    "activities to fill your days in", 
    		    "how to structure your itinerary", 
    		    "trip timeline for", 
    		    "itinerary for a week in", 
    		    "detailed trip plan for", 
    		    "how to plan a week in", 
    		    "suggested day-by-day schedule", 
    		    "best plan for a visit to", 
    		    "ideal itinerary for a short trip", 
    		    "how to organize your days in", 
    		    "how to make the most of your time in", 
    		    "complete trip schedule for", 
    		    "how to plan a two-week trip to", 
    		    "itinerary tips for", 
    		    "how to plan a weekend trip to", 
    		    "suggested plan for sightseeing in", 
    		    "recommended day trips from", 
    		    "activities to do each day of the week", 
    		    "how to allocate your days in", 
    		    "best way to plan a vacation to", 
    		    "recommended daily schedule for", 
    		    "how to design your travel itinerary", 
    		    "trip plan breakdown for", 
    		    "how to fit everything in your itinerary", 
    		    "suggested travel schedule", 
    		    "optimal way to plan your trip to", 
    		    "how to create an itinerary for a city break", 
    		    "travel plan for a week-long trip", 
    		    "best itinerary for a holiday in", 
    		    "how to plan a long weekend in", 
    		    "detailed day-by-day plan for", 
    		    "suggested itinerary for exploring", 
    		    "how to schedule sightseeing in", 
    		    "itinerary tips for a successful trip"
    		));

		intentMap.put("GetCurrencyLanguageInfo", Arrays.asList(
    		    "currency in", 
    		    "exchange money", 
    		    "speak language", 
    		    "say in", 
    		    "currency used in", 
    		    "money used in", 
    		    "local currency", 
    		    "current exchange rate", 
    		    "how to exchange money", 
    		    "money conversion in", 
    		    "language spoken in", 
    		    "what language is spoken in", 
    		    "official language of", 
    		    "how to say in", 
    		    "local language", 
    		    "currency exchange", 
    		    "currency details for", 
    		    "language spoken locally", 
    		    "currency information for", 
    		    "how to convert currency in", 
    		    "main language in", 
    		    "exchange rate for", 
    		    "what currency do they use in", 
    		    "language used in", 
    		    "local currency used in", 
    		    "common language in", 
    		    "money exchange rate", 
    		    "how much is currency worth in", 
    		    "what currency do they accept in", 
    		    "how to say 'hello' in", 
    		    "how to speak in", 
    		    "what is the currency in", 
    		    "currency and language in", 
    		    "currency information", 
    		    "what's the local language in", 
    		    "which language to use in", 
    		    "currency and exchange rates", 
    		    "language for visitors in", 
    		    "currency details for visiting", 
    		    "how to speak local language in", 
    		    "currency used for transactions in", 
    		    "local language tips for", 
    		    "currency symbols in", 
    		    "how to get local currency", 
    		    "what is the exchange rate for", 
    		    "language translation for", 
    		    "how to convert your money", 
    		    "currency denominations in", 
    		    "exchange currency for", 
    		    "how to handle currency exchange", 
    		    "language phrases for", 
    		    "currency guide for", 
    		    "how to speak common phrases in", 
    		    "currency conversion guide", 
    		    "what's the money situation in", 
    		    "how to use currency in", 
    		    "language help in", 
    		    "how to deal with currency exchange", 
    		    "money exchange options in", 
    		    "currency and language guide for", 
    		    "how to get cash in", 
    		    "currency exchange tips for", 
    		    "language assistance in", 
    		    "best way to exchange currency in", 
    		    "how to handle foreign currency", 
    		    "currency exchange locations in", 
    		    "how to manage money in", 
    		    "language services in", 
    		    "best currency exchange rates in", 
    		    "how to get foreign currency in", 
    		    "language tips for travelers", 
    		    "currency usage tips in", 
    		    "how to say basic phrases in", 
    		    "currency and language essentials for", 
    		    "how to exchange cash in", 
    		    "currency and language basics"
    		));
    	intentMap.put("GetTravelRequirements", Arrays.asList(
    		    "visa for", 
    		    "travel restrictions", 
    		    "entry requirements", 
    		    "covid rules", 
    		    "travel documents needed for", 
    		    "entry visa", 
    		    "what documents do I need to travel to", 
    		    "passport requirements for", 
    		    "visa application process for", 
    		    "covid travel guidelines", 
    		    "health requirements for", 
    		    "what are the travel restrictions for", 
    		    "travel rules for entering", 
    		    "quarantine rules for", 
    		    "travel permits for", 
    		    "entry regulations for", 
    		    "visa information for", 
    		    "covid restrictions for", 
    		    "requirements for traveling to", 
    		    "health and safety guidelines for", 
    		    "entry rules for", 
    		    "covid testing requirements for", 
    		    "visa policy for", 
    		    "current travel regulations for", 
    		    "how to apply for a visa for", 
    		    "travel advisories for", 
    		    "travel entry requirements for", 
    		    "what do I need to enter", 
    		    "travel entry guidelines for", 
    		    "health certificates for", 
    		    "travel requirements during covid", 
    		    "visa details for", 
    		    "covid travel restrictions", 
    		    "entry permissions for", 
    		    "travel documentation for", 
    		    "what to know before traveling to", 
    		    "visa and health requirements for", 
    		    "requirements for entry into", 
    		    "travel restrictions due to covid", 
    		    "visa regulations for", 
    		    "covid rules for travelers to", 
    		    "entry documentation for", 
    		    "travel restrictions and requirements for", 
    		    "quarantine and travel rules", 
    		    "travel health requirements for", 
    		    "travel safety guidelines for", 
    		    "current entry requirements for", 
    		    "visa and travel restrictions for", 
    		    "covid travel entry requirements", 
    		    "requirements for traveling during covid", 
    		    "visa necessities for", 
    		    "what to prepare for travel to", 
    		    "travel safety and health regulations", 
    		    "entry requirements during covid", 
    		    "how to meet entry requirements for", 
    		    "visa and quarantine requirements for", 
    		    "what you need to travel to", 
    		    "travel documentation and restrictions", 
    		    "current visa requirements for", 
    		    "entry and health guidelines for", 
    		    "covid entry guidelines for", 
    		    "what are the entry requirements for", 
    		    "quarantine and health requirements for", 
    		    "travel advisories and restrictions for", 
    		    "visa and health regulations for", 
    		    "travel requirements and guidelines for", 
    		    "travel documentation and entry rules for", 
    		    "passport and visa requirements for", 
    		    "health and travel regulations for", 
    		    "entry and covid guidelines for", 
    		    "covid travel and entry guidelines", 
    		    "visa requirements and travel rules for", 
    		    "travel requirements and safety protocols", 
    		    "entry rules and health measures for", 
    		    "travel entry and covid regulations", 
    		    "current entry and travel requirements", 
    		    "visa and covid entry rules", 
    		    "travel regulations and health guidelines", 
    		    "what documents for entry into", 
    		    "current travel and visa requirements", 
    		    "covid restrictions and entry rules", 
    		    "entry conditions for travelers to", 
    		    "what to know for traveling to", 
    		    "visa and travel conditions for", 
    		    "travel documentation and visa rules", 
    		    "current requirements for entry and travel", 
    		    "entry and visa process for", 
    		    "health and entry requirements for", 
    		    "covid travel documentation for", 
    		    "travel health and visa requirements"
    		));
    	intentMap.put("GetWeatherInfo", Arrays.asList(
    		    "weather in", 
    		    "current weather", 
    		    "temperature in", 
    		    "forecast in", 
    		    "weather report for", 
    		    "what's the weather like in", 
    		    "weather conditions in", 
    		    "today's weather in", 
    		    "temperature today in", 
    		    "weather update for", 
    		    "what is the temperature in", 
    		    "weather forecast for", 
    		    "current temperature in", 
    		    "weather overview for", 
    		    "weather status in", 
    		    "climate in", 
    		    "weather details for", 
    		    "weather predictions for", 
    		    "weather info for", 
    		    "how's the weather in", 
    		    "weather outlook for", 
    		    "temperature forecast in", 
    		    "weather trends in", 
    		    "weather situation in", 
    		    "current weather conditions in", 
    		    "what's the forecast in", 
    		    "temperature report for", 
    		    "weather conditions today in", 
    		    "weather update today for", 
    		    "what's the weather forecast for", 
    		    "weather information for", 
    		    "current forecast for", 
    		    "temperature details for", 
    		    "what's the weather going to be like in", 
    		    "daily weather forecast for", 
    		    "weather for the week in", 
    		    "current climate in", 
    		    "what's the current weather in", 
    		    "how's the temperature in", 
    		    "weather forecast details for", 
    		    "weather overview today in", 
    		    "what's the weather prediction for", 
    		    "temperature overview for", 
    		    "weather and climate in", 
    		    "how's the weather expected to be in", 
    		    "weather trends and forecast for", 
    		    "current weather information for", 
    		    "weather conditions next week in", 
    		    "temperature trends in", 
    		    "weather situation today in", 
    		    "current weather status in", 
    		    "weekly weather forecast for", 
    		    "weather information and forecast for", 
    		    "what's the weather like today in", 
    		    "current weather details for", 
    		    "how's the weather this week in", 
    		    "weather predictions for the week in", 
    		    "what's the daily weather like in", 
    		    "temperature and weather info for", 
    		    "how's the weather forecast this week in", 
    		    "weather overview for the day in", 
    		    "climate details for", 
    		    "weather forecast and conditions for", 
    		    "what's the daily temperature in", 
    		    "current weather and temperature in", 
    		    "current weather status for", 
    		    "weather outlook today in", 
    		    "temperature and weather conditions for", 
    		    "what's the weather outlook for", 
    		    "weekly temperature forecast in", 
    		    "current and upcoming weather in", 
    		    "weather forecast for the month in", 
    		    "weather details today for", 
    		    "weather status and forecast for", 
    		    "what's the temperature forecast for", 
    		    "current temperature and weather for", 
    		    "weather overview for the week in", 
    		    "current weather summary for", 
    		    "temperature details and forecast for", 
    		    "what's the climate forecast for", 
    		    "weather predictions for the month in", 
    		    "how's the weather this month in", 
    		    "weekly weather and temperature info for", 
    		    "current weather conditions and forecast for", 
    		    "daily temperature and weather for", 
    		    "what's the long-term weather forecast for", 
    		    "weather and temperature outlook for", 
    		    "what's the weather summary for", 
    		    "current and future temperature in", 
    		    "weather trends and details for", 
    		    "how's the daily weather forecast in", 
    		    "weekly weather and climate information for", 
    		    "monthly weather forecast for", 
    		    "current weather and forecast details for"
    		));
    	intentMap.put("GetEmergencyInfo", Arrays.asList(
    		    "emergency number", 
    		    "nearest hospital", 
    		    "lost passport", 
    		    "urgent contact", 
    		    "emergency contact", 
    		    "local emergency number", 
    		    "emergency services", 
    		    "emergency hotline", 
    		    "hospital contact information", 
    		    "what to do if you lose your passport", 
    		    "emergency assistance", 
    		    "how to report a lost passport", 
    		    "local police station", 
    		    "emergency numbers for", 
    		    "where is the nearest hospital", 
    		    "medical emergencies", 
    		    "contact for lost passport", 
    		    "urgent medical help", 
    		    "emergency contacts in", 
    		    "hospital emergency services", 
    		    "how to get emergency help", 
    		    "report lost passport to", 
    		    "nearest clinic", 
    		    "emergency numbers in", 
    		    "urgent help contact", 
    		    "who to call in an emergency", 
    		    "local emergency services", 
    		    "emergency numbers abroad", 
    		    "hospital and emergency services", 
    		    "what to do in an emergency", 
    		    "how to reach emergency services", 
    		    "contact details for emergency", 
    		    "local emergency contacts", 
    		    "where to find emergency help", 
    		    "urgent contact information", 
    		    "how to handle a lost passport", 
    		    "nearest emergency facility", 
    		    "emergency assistance numbers", 
    		    "local emergency contacts in", 
    		    "what to do if passport is lost", 
    		    "nearest medical facility", 
    		    "report emergency to", 
    		    "urgent contact details", 
    		    "local emergency services contact", 
    		    "how to get emergency contact info", 
    		    "medical emergency numbers", 
    		    "nearest emergency center", 
    		    "how to get emergency medical help", 
    		    "report lost passport contact", 
    		    "emergency contact numbers", 
    		    "hospital contact numbers", 
    		    "emergency help abroad", 
    		    "contact for urgent assistance", 
    		    "how to reach local emergency services", 
    		    "lost passport procedures", 
    		    "urgent medical contact", 
    		    "nearest emergency medical services", 
    		    "emergency phone numbers", 
    		    "local emergency facility", 
    		    "how to contact emergency services", 
    		    "nearest help center", 
    		    "report emergency situations", 
    		    "urgent assistance contacts", 
    		    "how to get urgent help", 
    		    "emergency support number", 
    		    "local medical emergencies", 
    		    "contact for emergency medical services", 
    		    "hospital emergency contact", 
    		    "what to do in case of an emergency", 
    		    "nearest urgent care", 
    		    "emergency number abroad", 
    		    "who to contact for emergencies", 
    		    "medical emergency contact", 
    		    "emergency services for tourists", 
    		    "how to find emergency services", 
    		    "report lost documents", 
    		    "emergency medical help in", 
    		    "nearest emergency medical center", 
    		    "who to call for lost passport", 
    		    "urgent help for tourists", 
    		    "emergency procedures for", 
    		    "medical emergency procedures", 
    		    "local emergency support", 
    		    "how to report an emergency", 
    		    "urgent contact for", 
    		    "local emergency numbers and contacts", 
    		    "how to get emergency assistance", 
    		    "nearest emergency help center", 
    		    "emergency help numbers", 
    		    "how to get urgent medical assistance", 
    		    "report lost passport procedures", 
    		    "emergency services contact information", 
    		    "local emergency response", 
    		    "how to find urgent help", 
    		    "medical assistance contact", 
    		    "emergency response contacts", 
    		    "how to contact urgent services", 
    		    "emergency numbers and procedures", 
    		    "urgent help services", 
    		    "local contacts for urgent help", 
    		    "emergency contact procedures", 
    		    "how to get emergency support", 
    		    "nearest urgent help center", 
    		    "who to call for urgent help", 
    		    "how to report medical emergencies", 
    		    "emergency response numbers", 
    		    "urgent assistance procedures", 
    		    "local medical support", 
    		    "how to get emergency assistance abroad", 
    		    "emergency medical contact information", 
    		    "reporting lost passport procedures", 
    		    "emergency contact resources", 
    		    "nearest emergency response center", 
    		    "how to find emergency medical help", 
    		    "local urgent contact information"
    		));
    }

    public String classifyIntent(String userInput) {
        userInput = userInput.toLowerCase();
        
        for (Map.Entry<String, List<String>> entry : intentMap.entrySet()) {
            for (String keyword : entry.getValue()) {
                if (userInput.contains(keyword)) {
                    return entry.getKey();
                }
            }
        }
        return "UnknownIntent";
    }

//    public static void main(String[] args) {
//        IntentClassifier classifier = new IntentClassifier();
//
//        // Example user inputs
//        String[] testInputs = {
//            "What are the must-see places in Paris?",
//            "Tell me about Tokyo.",
//            "What's the weather like in New York?",
//            "How do I get around in Berlin?",
//            "Can you suggest a 3-day itinerary for Rome?"
//        };
//
//        for (String input : testInputs) {
//            String intent = classifier.classifyIntent(input);
//            System.out.println("User Input: \"" + input + "\" classified as: " + intent);
//        }
    }

